<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\Categories\Commands\**" />
    <Compile Remove="Features\Products\Commands\**" />
    <Compile Remove="Features\ProductVariants\Commands\**" />
    <EmbeddedResource Remove="Features\Categories\Commands\**" />
    <EmbeddedResource Remove="Features\Products\Commands\**" />
    <EmbeddedResource Remove="Features\ProductVariants\Commands\**" />
    <None Remove="Features\Categories\Commands\**" />
    <None Remove="Features\Products\Commands\**" />
    <None Remove="Features\ProductVariants\Commands\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyApp.Domain\MyApp.Domain.csproj" />
  </ItemGroup>

</Project>
